# Generated by Django 5.2.8 on 2025-11-15 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='author',
        ),
    ]
